// Exercise library with ~40 exercises for rehab and fitness

import { Exercise } from '@/types';

export const exercises: Exercise[] = [
  // ============ REHAB EXERCISES ============
  {
    id: 'pendulum',
    name: 'Pendulum Swings',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Lean forward, let arm hang. Make small circles clockwise, then counterclockwise.',
    sets: '2-3',
    reps: '10 each direction',
  },
  {
    id: 'passive-flexion',
    name: 'Passive Forward Flexion',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Use good arm to lift affected arm forward. Go only to comfortable range.',
    sets: '3',
    reps: '10',
  },
  {
    id: 'wand-abduction',
    name: 'Wand Abduction',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Hold wand/stick with both hands. Use good arm to push affected arm out to side.',
    sets: '3',
    reps: '10',
  },
  {
    id: 'supine-er',
    name: 'Supine External Rotation',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: true,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Lie on back, elbow at 90°. Gently rotate forearm outward using wand assistance.',
    sets: '3',
    reps: '10',
  },
  {
    id: 'isometric-er',
    name: 'Isometric External Rotation',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: true,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Stand sideways to wall, elbow bent 90°. Push back of hand into wall for 5-10 sec.',
    sets: '3',
    reps: '10',
    duration: '5-10 sec hold',
  },
  {
    id: 'isometric-ir',
    name: 'Isometric Internal Rotation',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Stand sideways to wall, elbow bent 90°. Push palm into wall for 5-10 sec.',
    sets: '3',
    reps: '10',
    duration: '5-10 sec hold',
  },
  {
    id: 'band-er',
    name: 'Band External Rotation',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 3,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: true,
    minAbductionAngle: 0,
    minFlexionAngle: 30,
    instructions: 'Elbow at side, bent 90°. Rotate forearm outward against light band resistance.',
    sets: '3',
    reps: '15',
  },
  {
    id: 'band-ir',
    name: 'Band Internal Rotation',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 3,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 30,
    instructions: 'Elbow at side, bent 90°. Rotate forearm inward against light band resistance.',
    sets: '3',
    reps: '15',
  },
  {
    id: 'scap-squeeze',
    name: 'Scapular Squeezes',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Squeeze shoulder blades together, hold 5 sec. Keep shoulders down.',
    sets: '3',
    reps: '10',
    duration: '5 sec hold',
  },
  {
    id: 'wall-slides',
    name: 'Wall Slides',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 3,
    requiresOverhead: true,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 90,
    minFlexionAngle: 90,
    instructions: 'Stand facing wall. Slide arms up wall keeping contact. Go only to comfortable range.',
    sets: '3',
    reps: '10',
  },
  {
    id: 'prone-y',
    name: 'Prone Y Raises',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 4,
    requiresOverhead: true,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 120,
    minFlexionAngle: 120,
    instructions: 'Lie face down. Lift arms in Y position with thumbs up. Keep light.',
    sets: '3',
    reps: '10',
  },
  {
    id: 'prone-t',
    name: 'Prone T Raises',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 4,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 90,
    minFlexionAngle: 0,
    instructions: 'Lie face down. Lift arms straight out to sides (T position) with thumbs up.',
    sets: '3',
    reps: '10',
  },
  {
    id: 'sleeper-stretch',
    name: 'Sleeper Stretch',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 90,
    instructions: 'Lie on affected side, arm forward. Use other hand to gently push wrist toward floor.',
    sets: '3',
    duration: '30 sec hold',
  },
  {
    id: 'cross-body-stretch',
    name: 'Cross Body Stretch',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 60,
    instructions: 'Pull affected arm across body with other hand. Hold gentle stretch.',
    sets: '3',
    duration: '30 sec hold',
  },
  {
    id: 'wall-walk-flexion',
    name: 'Wall Finger Walk (Flexion)',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Stand facing wall, fingertips touching at waist height. Walk fingers up wall as high as comfortable. Hold 2-3 sec at top, walk back down.',
    sets: '2',
    reps: '10',
  },
  {
    id: 'wall-walk-abduction',
    name: 'Wall Finger Walk (Abduction)',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Stand with affected side toward wall, fingertips at hip height. Walk fingers up wall sideways as high as comfortable. Hold 2-3 sec at top, walk back down.',
    sets: '2',
    reps: '10',
  },
  {
    id: 'table-slide',
    name: 'Table Slide',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Sit at table, place cloth or towel under forearm. Lean forward and slide arm forward along table toward 90°. Let gravity and momentum do the work. Slide back.',
    sets: '2',
    reps: '10',
  },
  {
    id: 'door-pulley',
    name: 'Over-Door Pulley Flexion',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Use over-door pulley or rope looped over door. Good arm pulls rope to passively lift affected arm. Lower slowly and with control.',
    sets: '3',
    reps: '10',
  },
  {
    id: 'shoulder-shrugs',
    name: 'Shoulder Shrugs',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Slowly shrug both shoulders up toward ears, hold 2 sec, lower. Keep movement controlled and symmetrical.',
    sets: '3',
    reps: '15',
  },
  {
    id: 'shoulder-rolls',
    name: 'Shoulder Rolls',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Gently roll both shoulders forward in large slow circles, then reverse direction. Move only within pain-free range.',
    sets: '2',
    reps: '10 each direction',
  },
  {
    id: 'er-wall-stretch',
    name: 'External Rotation Wall Stretch',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: true,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Stand with elbow bent 90°, forearm flat on wall at shoulder height. Slowly rotate body away from wall ~45° until you feel a gentle stretch in the front of the shoulder. Hold.',
    sets: '3',
    duration: '30 sec hold',
  },
  {
    id: 'sidelying-er',
    name: 'Side-Lying External Rotation',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: true,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Lie on good side, affected arm on top, elbow bent 90°. Slowly rotate forearm upward keeping elbow tucked at side. Use no weight initially, progress to 0.5-1 kg.',
    sets: '3',
    reps: '10-15',
  },
  {
    id: 'doorway-pec-stretch',
    name: 'Doorway Pec Stretch',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 60,
    minFlexionAngle: 60,
    instructions: 'Stand in doorway, forearm resting on frame at shoulder height. Gently lean body forward to stretch front of shoulder and chest. Keep elbow at 90°.',
    sets: '3',
    duration: '30 sec hold',
  },
  {
    id: 'posterior-capsule-stretch',
    name: 'Posterior Capsule Stretch',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 60,
    instructions: 'Bring affected arm across chest at shoulder height. Use other hand to gently pull elbow toward opposite shoulder until you feel a stretch in the back of the shoulder. Hold.',
    sets: '3',
    duration: '30 sec hold',
  },
  {
    id: 'towel-ir-stretch',
    name: 'Towel Internal Rotation Stretch',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 30,
    instructions: 'Hold towel overhead with good arm. Affected arm reaches behind back and grips lower end of towel. Good arm gently pulls up to stretch internal rotation range. Hold.',
    sets: '3',
    duration: '30 sec hold',
  },
  {
    id: 'active-flexion',
    name: 'Active Forward Flexion',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 45,
    instructions: 'Standing, raise arm forward with thumb up to shoulder height (90°). Lower slowly. Go only to comfortable range. No weight initially.',
    sets: '3',
    reps: '10',
  },
  {
    id: 'active-abduction',
    name: 'Active Abduction',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 30,
    minFlexionAngle: 0,
    instructions: 'Standing, raise arm out to side with thumb up to shoulder height (90°). Lower slowly. Keep elbow slightly soft. No weight initially.',
    sets: '3',
    reps: '10',
  },
  {
    id: 'empty-can',
    name: 'Empty Can Raises',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 3,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 60,
    minFlexionAngle: 60,
    instructions: 'Raise arm in scapular plane (30° forward of side) to shoulder height with thumb pointing down. Lower slowly. Light weight only.',
    sets: '3',
    reps: '10-12',
  },
  {
    id: 'full-can',
    name: 'Full Can Raises',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 3,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 60,
    minFlexionAngle: 60,
    instructions: 'Raise arm in scapular plane (30° forward of side) to shoulder height with thumb pointing up. Lower slowly. Light weight.',
    sets: '3',
    reps: '10-12',
  },
  {
    id: 'sidelying-ir',
    name: 'Side-Lying Internal Rotation',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 3,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 30,
    instructions: 'Lie on affected side, elbow bent 90°, forearm pointing up toward ceiling. Slowly rotate forearm down toward floor. Use no weight or very light weight.',
    sets: '3',
    reps: '10-15',
  },
  {
    id: 'wall-pushup-plus',
    name: 'Wall Push-Up Plus',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 3,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 90,
    instructions: 'Hands on wall at shoulder height. Perform a wall push-up, then at the top push chest further from wall by spreading shoulder blades apart (protraction). This activates serratus anterior.',
    sets: '3',
    reps: '10-15',
  },
  {
    id: 'pnf-diagonal-d2',
    name: 'PNF D2 Diagonal Pattern',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 3,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: true,
    minAbductionAngle: 60,
    minFlexionAngle: 60,
    instructions: 'Start with arm across body low (toward opposite hip). Sweep diagonally up and outward, rotating palm up. Reverse slowly back down. Use light band or no resistance.',
    sets: '3',
    reps: '10',
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raises',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 3,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 60,
    minFlexionAngle: 0,
    instructions: 'Raise arms out to sides to shoulder height, thumbs slightly up. Lower slowly. Start very light (0.5-1 kg). Do not shrug at top.',
    sets: '3',
    reps: '10-12',
  },
  {
    id: 'posterior-delt-fly',
    name: 'Bent-Over Posterior Fly',
    category: 'rehab',
    targetArea: 'shoulder',
    difficulty: 4,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 60,
    minFlexionAngle: 60,
    instructions: 'Hinge forward at hips, arms hanging down with light weights. Raise arms out to sides with thumbs up, squeezing shoulder blades together at top. Very light weight.',
    sets: '3',
    reps: '10-12',
  },

  // ============ MOBILITY EXERCISES ============
  {
    id: 'cat-cow',
    name: 'Cat-Cow',
    category: 'mobility',
    targetArea: 'full-body',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'On hands and knees. Arch back up (cat), then drop belly down (cow).',
    sets: '2',
    reps: '10',
  },
  {
    id: 'thoracic-rotation',
    name: 'Thoracic Rotation',
    category: 'mobility',
    targetArea: 'full-body',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Side-lying with knees bent. Rotate upper body, following hand with eyes.',
    sets: '2',
    reps: '10 each side',
  },

  // ============ CARDIO EXERCISES ============
  {
    id: 'stationary-bike',
    name: 'Stationary Bike',
    category: 'cardio',
    targetArea: 'legs',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Keep arm supported if in sling. Adjust intensity as tolerated.',
    duration: '20-45 min',
  },
  {
    id: 'walking',
    name: 'Walking',
    category: 'cardio',
    targetArea: 'legs',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Brisk walking. Keep arm protected if recovering.',
    duration: '20-60 min',
  },
  {
    id: 'elliptical-no-arms',
    name: 'Elliptical (No Arms)',
    category: 'cardio',
    targetArea: 'legs',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 30,
    instructions: 'Use elliptical without holding arm handles. Hold center bar for balance.',
    duration: '20-40 min',
  },
  {
    id: 'running',
    name: 'Running',
    category: 'cardio',
    targetArea: 'legs',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 30,
    minFlexionAngle: 30,
    instructions: 'Running/jogging. Only when cleared and arm swing is comfortable.',
    duration: '20-60 min',
  },
  {
    id: 'swimming-kick',
    name: 'Pool Kick Board',
    category: 'cardio',
    targetArea: 'legs',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 60,
    instructions: 'Use kickboard, letting shoulder arm rest. Kicking only.',
    duration: '20-30 min',
  },
  {
    id: 'rowing-light',
    name: 'Light Rowing',
    category: 'cardio',
    targetArea: 'full-body',
    difficulty: 3,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 60,
    minFlexionAngle: 90,
    instructions: 'Very light resistance. Stop if any shoulder discomfort.',
    duration: '15-30 min',
  },

  // ============ STRENGTH - LEGS ============
  {
    id: 'leg-press',
    name: 'Leg Press Machine',
    category: 'strength',
    targetArea: 'legs',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Seated leg press. Shoulder stays supported against pad.',
    sets: '3-4',
    reps: '10-12',
  },
  {
    id: 'leg-curl',
    name: 'Seated Leg Curl',
    category: 'strength',
    targetArea: 'legs',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Seated hamstring curl machine.',
    sets: '3',
    reps: '12-15',
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    category: 'strength',
    targetArea: 'legs',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Seated leg extension machine.',
    sets: '3',
    reps: '12-15',
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    category: 'strength',
    targetArea: 'legs',
    difficulty: 3,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 60,
    minFlexionAngle: 90,
    instructions: 'Hold dumbbell at chest. Only if shoulder can tolerate front rack position.',
    sets: '3',
    reps: '10-12',
  },
  {
    id: 'bodyweight-squat',
    name: 'Bodyweight Squat',
    category: 'strength',
    targetArea: 'legs',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Arms crossed at chest or at sides. Full depth as comfortable.',
    sets: '3',
    reps: '15-20',
  },
  {
    id: 'walking-lunge',
    name: 'Walking Lunges',
    category: 'strength',
    targetArea: 'legs',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Bodyweight walking lunges. Keep arms at sides or on hips.',
    sets: '3',
    reps: '12 each leg',
  },
  {
    id: 'calf-raise',
    name: 'Standing Calf Raises',
    category: 'strength',
    targetArea: 'legs',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Rise up on toes, lower slowly. Use wall for balance if needed.',
    sets: '3',
    reps: '15-20',
  },
  {
    id: 'single-leg-rdl',
    name: 'Single Leg RDL',
    category: 'strength',
    targetArea: 'legs',
    difficulty: 3,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Hinge at hip on one leg. Can hold light weight on good side if stable.',
    sets: '3',
    reps: '8-10 each leg',
  },

  // ============ STRENGTH - CORE ============
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    category: 'strength',
    targetArea: 'core',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 90,
    instructions: 'On back, arms up. Extend opposite arm/leg while keeping back flat.',
    sets: '3',
    reps: '10 each side',
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    category: 'strength',
    targetArea: 'core',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 30,
    minFlexionAngle: 60,
    instructions: 'On hands and knees. Extend opposite arm and leg. Keep core tight.',
    sets: '3',
    reps: '10 each side',
  },
  {
    id: 'forearm-plank',
    name: 'Forearm Plank',
    category: 'strength',
    targetArea: 'core',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 60,
    instructions: 'Hold plank on forearms. Keep body in straight line.',
    sets: '3',
    duration: '20-60 sec',
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    category: 'strength',
    targetArea: 'core',
    difficulty: 3,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'Support on forearm, stack feet. Do on good arm side first.',
    sets: '2-3',
    duration: '20-45 sec each side',
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    category: 'strength',
    targetArea: 'core',
    difficulty: 1,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'On back, knees bent. Lift hips, squeeze glutes at top.',
    sets: '3',
    reps: '15',
  },
  {
    id: 'pallof-press',
    name: 'Pallof Press',
    category: 'strength',
    targetArea: 'core',
    difficulty: 3,
    requiresOverhead: false,
    requiresShoulderLoading: true,
    requiresExternalRotation: false,
    minAbductionAngle: 30,
    minFlexionAngle: 60,
    instructions: 'Hold cable/band at chest. Press out and hold against rotation. Light resistance.',
    sets: '3',
    reps: '10 each side',
  },
  {
    id: 'hollow-hold',
    name: 'Hollow Body Hold',
    category: 'strength',
    targetArea: 'core',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 0,
    instructions: 'On back, legs straight, arms at sides or on thighs. Press lower back to floor.',
    sets: '3',
    duration: '20-45 sec',
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    category: 'strength',
    targetArea: 'core',
    difficulty: 2,
    requiresOverhead: false,
    requiresShoulderLoading: false,
    requiresExternalRotation: false,
    minAbductionAngle: 0,
    minFlexionAngle: 60,
    instructions: 'Seated, lean back slightly. Rotate torso side to side. No weight if shoulder sensitive.',
    sets: '3',
    reps: '20 total',
  },
];

export function getExerciseById(id: string): Exercise | undefined {
  return exercises.find(e => e.id === id);
}

export function getExercisesByCategory(category: Exercise['category']): Exercise[] {
  return exercises.filter(e => e.category === category);
}

export function getRehabExercises(): Exercise[] {
  return exercises.filter(e => e.category === 'rehab' || e.category === 'mobility');
}

export function getCardioExercises(): Exercise[] {
  return exercises.filter(e => e.category === 'cardio');
}

export function getStrengthExercises(): Exercise[] {
  return exercises.filter(e => e.category === 'strength');
}
